graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    subscriptions:
      websocket:
        path: /subscriptions

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  cdn:
    enabled: false
    version: 0.11.11
